### ISSUE TITLE
Minor error in SEPMAC.cnf.xml for 8841

### ISSUE THREAD

**Issue by steve-lad** [usecallmanagernz/usecallmanagernz.github.io#3]
Excellent documentation. A very minor note that applies to 8841.

"authName" must be declared as in the sip.conf as this is used for the user in the digest for registration. The phone does not fall back to "name" and the phone tries to register with <> in the digest which asterisk rejects.

`chan_sip.c: username mismatch, have <1002>, digest has <>`

Hope this helps.

**Comment by gareth-palmer** [comment]
Thanks, it may have just been the 7900 series that behaved that way. I will update the docs.
