### ISSUE TITLE
Asterisk version

### ISSUE THREAD

**Issue by DIGIVOIP** [usecallmanagernz/usecallmanagernz.github.io#5]
Hello 

Firstofall, thank you for your great work.
I just want to ask in case of patching asterisk 18.20.2 , you mention that we should use the last patch 18.21.0 is this correct ?or we should use the same exact version .I see only 18.20.0.

**Comment by gareth-palmer** [comment]
The 18.20.0 patch should apply cleanly to Asterisk 18.20.2.
